services:
  mongodb:
    image: mongo:latest
    container_name: weather-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend/src/js
    container_name: weather-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/src
    container_name: weather-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mongo-data: